name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get version info
        id: vars
        run: |
          SHA=$(git rev-parse --short HEAD)
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [ -n "$TAG" ]; then
            echo "version=$TAG ($SHA)" >> $GITHUB_OUTPUT
          else
            echo "version=$SHA" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      # Cache the dist directory
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            dist
            node_modules/.vite
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.vue') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        env:
          VITE_COMMIT_SHA: ${{ steps.vars.outputs.version }}
        run: npm run build

      - name: Update index.html title
        run: |
          sed -i "s/<title>BRAT Annotation Checker<\/title>/<title>BRAT Annotation Checker (${{ steps.vars.outputs.version }})<\/title>/" dist/index.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4